# Generated by Django 2.1.1 on 2019-06-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_organize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organize',
            name='category',
        ),
        migrations.RemoveField(
            model_name='organize',
            name='post',
        ),
        migrations.DeleteModel(
            name='Organize',
        ),
    ]
